
name: example-ngrok-go-v2
on:
  workflow_dispatch:

jobs:
  example-ngrok-go-v2:
    name: Build
    runs-on: ubuntu-latest
    steps:



    - uses: shaowenchen/debugger-action@v2
      name: debugger
      timeout-minutes: 300
      continue-on-error: true
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
